### ISSUE TITLE
Can't revoke API Tokens in CKAN 2.9.3

### ISSUE THREAD

**Issue by markstuart** [qld-gov-au/ckanext-csrf-filter#19]
2.9.x now provides a management interface for creating and revoking api tokens. The creation of tokens works fine, but when I try to revoke token I get a 403 page with "Your form submission could not be validated".

I haven't really been able to dig into it at this point, but thought I'd report and see if you're aware of the problem or have seen other situations where seemingly valid forms fail csrf validation.

```
Request URL: https://catalogue.data.govt.nz/user/my_user/api-tokens/bOmsFdClNB2m_LTR5rBurMYzTGSu-0SBwYIv05yy1zY/revoke
Request Method: POST
Status Code: 403 
```

**Comment by JVickery-TBS** [comment]
The core ckan feature of the JS modal for confirming an action, by default, will just use an appended form with JUST the action to the form and not other form fields:
```
    /* Performs the action for the current item.
     *
     * Returns nothing.
     */
    performAction: function () {
      // create a form and submit it to confirm the deletion
      var form = jQuery('<form/>', {
        action: this.el.attr('href'),
        method: 'POST'
      });

      // use parent to el form if data-module-with-data == true
      if (this.options.withData) {
        var form = this.el.closest('form');
      }

      form.appendTo('body').submit();
    },
```

In this scenario, the revoke api key button has the attribute `data-module="confirm-action"` which is what creates the confirm action modal. You can add `data-module-with-data=true` html attribute to grab the entire form element for jQuery to use in the modal, this would include the token field.

Personally, I was able to achieve this in this scenario by extending the `user/snippets/api_token_list.html` template and adding the `data-module-with-data=true` attribute to the revoke button. 

Unfortunately, I do not think this is something that would be solvable in this extension code as it is to do with the JS in core. So for this issue, I think it is solvable by just extending templates as needed.

**Comment by markstuart** [comment]
Thanks for this feedback @JVickery-TBS, I'm now overriding the `user/snippets/api_token_list.html` like this:
```html
{% ckan_extends %}

{% block token_cell_actions %}
<td>
  {% set action = h.url_for("user.api_token_revoke", id=user['name'], jti=token['id']) %}
  <form action="{{ action }}" method="POST">
{{ h.csrf_input() }}
    <div class="btn-group">
      <button type="submit" href="{{ action }}" class="btn btn-danger btn-sm" title="{{ _('Revoke') }}" data-module="confirm-action" data-module-with-data=true>
        <i class="fa fa-times"></i>
      </button>
    </div>
  </form>
</td>
{% endblock token_cell_actions %}
```
and that works fine.
