### ISSUE TITLE
Add SameSite attribute to token cookies

### ISSUE THREAD

**Issue by ThrawnCA** [qld-gov-au/ckanext-csrf-filter#28]
For defence in depth, it would be best to configure the SameSite attribute on token cookies, so that they're harder to misuse across sites. `SameSite=Strict` should work.

**Comment by JVickery-TBS** [comment]
Pull request to solve this issue is in now. Allows config option to set this value, but still defaults to 'None' as it did before.

**Comment by ThrawnCA** [comment]
Implemented in [1.2.0](https://github.com/qld-gov-au/ckanext-csrf-filter/releases/tag/1.2.0)
